# Generated by Django 2.1.1 on 2018-09-08 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image', '0003_auto_20180909_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow')], max_length=20)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='image.Comment')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications_by_creator', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='image.Image')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications_by_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
